### ISSUE TITLE
file index.html

### ISSUE THREAD

**Issue by waqaskanju** [masangana/TodoList#6]
issue 1:
![image](https://user-images.githubusercontent.com/13853450/172299335-d0642801-8c6a-4e21-ae81-a382ca8ba4e8.png)

try to install font awesome and bootstrap using webpack method.
THis is link for more info https://getbootstrap.com/docs/4.0/getting-started/webpack/

issue 2: 
![image](https://user-images.githubusercontent.com/13853450/172299501-3afe82a9-a458-45cd-b873-aa501457946a.png)
Try to stick to one convention. your id for  input field is input_text and your id for buttton is addTask.
In one method you are using underscore and in other you are using camelCase . Kindly stick to one convention.

**Comment by masangana** [comment]
Done
