### ISSUE TITLE
file index.js

### ISSUE THREAD

**Issue by waqaskanju** [masangana/TodoList#7]
Hi @masangana !

Good job so far! your project is almost complete.
![image](https://user-images.githubusercontent.com/13853450/189755716-02dcb461-1f2c-4d7d-b2c1-3078dead7079.png)

(Highlights) Good Points: 👍
You documented your work professionally. ✔
Gitflow is used correctly. ✔
All linters checks are ok. ✔

(Changes Required) Aspects to improve: ♻️

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

issue 1:
 Is not better to remove dead code in production? Some code is commented on but not removed.
![image](https://user-images.githubusercontent.com/13853450/172299887-7c1f9f37-6812-40c7-ad2f-ad840770368b.png)

issue 2: How about giving proper names to your functions? Your function name should be an action verb
I think there is no word in English, this word **lesTaches** does not convey any meaning.
![image](https://user-images.githubusercontent.com/13853450/172300285-954b74c5-5ef4-47bc-9924-7f72b100c284.png)

issue 3: Kindly make this code block  dry:
![image](https://user-images.githubusercontent.com/13853450/172303490-b482b528-95f4-47df-af24-256f6e2a9bfc.png)

Optional Changes
1- Kindly practice readability, in some lines you have left space before and after a comment but in some cases, there is no space. Try to stick to one convention.
![image](https://user-images.githubusercontent.com/13853450/189754400-2967eec0-695e-495c-b455-c6d231c68516.png)

**Comment by masangana** [comment]
solved
